barys: Adapt to new layer structure
We needed to have barys being able to build each separate git repositories such as
https://github.com/resin-io/resin-beaglebone

Signed-off-by: Florin Sarbu <florin@resin.io>

diff --git a/scripts/barys b/scripts/barys
--- a/scripts/barys
+++ b/scripts/barys
@@ -15,14 +15,11 @@
 # Signed-off-by: Andrei Gherzan <andrei@resin.io>
 #
 
-BARYSVERSION=1.2
-
-# JSON machine desciption file
-JSON=device-types.json
+BARYSVERSION=1.3
 
 # Default values
 COMPRESS_TOOL="xz"
-BUILDDIR=build
+BUILD_DIR=build
 REMOVEBUILD=no
 COMPRESS=no
 STAGING=no
@@ -35,22 +32,10 @@ RM_WORK=
 LOGFILE=`pwd`/`basename "$0"`.log
 MACHINES=
 BITBAKEARGS=
-YOCTO_VERSION=
 EXIT_CODE=0
 
 function help {
     echo "Usage: "`basename "$0"`" --yocto <yocto-version> [options]"
-
-    echo
-    echo -e "Mandatory arguments:"
-
-    echo -e "\t--yocto"
-    echo -e "\t\t Select yocto version. This flag restricts available"
-    echo -e "\t\t buildable machines based on yocto version."
-        echo -e "\t\t Supported yocto versions:"
-    for yoctover in ${YOCTO_VERSIONS}; do
-        echo -e "\t\t\t $yoctover"
-    done
 
     echo
     echo -e "Options:"
@@ -152,6 +137,16 @@ function log {
     fi
 }
 
+function check_machine {
+    found=0
+    for mi in ${SUPPORTED_MACHINES}; do
+        if [ "$1" == "$mi" ]; then
+            found=1
+            break
+        fi
+    done
+}
+
 # Timer
 STARTTIME=$(date +%s)
 
@@ -160,14 +155,20 @@ pushd `dirname $0` > /dev/null 2>&1
 SCRIPTPATH=`pwd`
 popd > /dev/null 2>&1
 
-# Get the supported yocto versions
-YOCTO_VERSIONS=$(ls $SCRIPTPATH/../../layers/poky/)
-if [ -z "$YOCTO_VERSIONS" ]; then
-    log ERROR "Cannot find yocto layers. Did you repo init/sync?"
-fi
-
 # Backup $@
 SCRIPT_ARGUMENTS=$@
+
+# get all the device type .json files
+DEVICE_TYPES_JSONS=$(ls $SCRIPTPATH/../../*.json | grep -v package.json)
+if [ -z "${DEVICE_TYPES_JSONS}" ]; then
+    log ERROR "No available .json. Please check your git repository."
+fi
+
+# Get the list of the supported machines out of all the available machine json files
+# (we may have multiple json files describing different machines based on the same resin layers; i.e. imx6 fsl based machines)
+for json in ${DEVICE_TYPES_JSONS}; do
+    SUPPORTED_MACHINES="${SUPPORTED_MACHINES} `jq -r "[.yocto.machine] | sort | .[] | select(. != null)" ${json}`"
+done
 
 # Parse arguments
 while [[ $# -ge 1 ]]; do
@@ -176,18 +177,6 @@ while [[ $# -ge 1 ]]; do
         -h|--help)
             help
             exit 0
-            ;;
-        --yocto)
-            if [ -z "$2" ]; then
-                log ERROR "\"$1\" argument needs a value."
-            fi
-            check_yoctoversion $2
-            if [ $found -eq 0 ]; then
-                log ERROR "\"$2\" is not a supported yocto version."
-            else
-                YOCTO_VERSION=$2
-                shift
-            fi
             ;;
         -m|--machine)
             if [ -z "$2" ]; then
@@ -224,7 +213,7 @@ while [[ $# -ge 1 ]]; do
             if [ -z "$2" ]; then
                 log ERROR "\"$1\" argument needs a value."
             fi
-            BUILDDIR=$2
+            BUILD_DIR=$2
             shift
             ;;
         --shared-downloads)
@@ -253,19 +242,6 @@ while [[ $# -ge 1 ]]; do
             RM_WORK=yes
             ;;
         -i|--interactive)
-            echo -n "Supported yocto versions:"
-            for yver in ${YOCTO_VERSIONS}; do
-                echo -n " $yver"
-            done
-            echo "."
-            read -p "Select yocto version: " yver
-            check_yoctoversion $yver
-            if [ $found -eq 0 ]; then
-                log ERROR "\"$m\" is not a supported yocto version."
-            fi
-            YOCTO_VERSION=$yver
-
-            echo "."
             read -p "Select machines. Space separated or empty for all: " m
             MACHINES=$m
             for m in $MACHINES; do
@@ -300,9 +276,9 @@ while [[ $# -ge 1 ]]; do
                 [Yy]* ) REMOVEBUILD=yes;;
             esac
 
-            read -p "Build name? [$BUILDDIR] " yn
+            read -p "Build name? [$BUILD_DIR] " yn
             if [ -n "$yn" ]; then
-                BUILDDIR=$yn
+                BUILD_DIR=$yn
             fi
 
             read -p "Shared downloads directory? yes/[no] " yn
@@ -360,10 +336,9 @@ if [ "z$LOG" == "zyes" ]; then
     date >> $LOGFILE
     echo "Script called from: "`pwd` >> $LOGFILE
     echo "Script called as: $0 $SCRIPT_ARGUMENTS" >> $LOGFILE
-    echo "Selected yocto version: $YOCTO_VERSION" >> $LOGFILE
     echo "Selected machines: $MACHINES" >> $LOGFILE
     echo "Selected bitbake arguments: $BITBAKEARGS" >> $LOGFILE
-    echo "Build directory name: $BUILDDIR" >> $LOGFILE
+    echo "Build directory name: $BUILD_DIR" >> $LOGFILE
     echo "Remove build directory? $REMOVEBUILD" >> $LOGFILE
     echo "Compressed image? $COMPRESS" >> $LOGFILE
     echo "Shared downloads directory: $SHARED_DOWNLOADS" >> $LOGFILE
@@ -375,20 +350,19 @@ if [ "z$LOG" == "zyes" ]; then
 fi
 
 if [ "x$REMOVEBUILD" == "xyes" ]; then
-    log "Removing old build in $SCRIPTPATH/../${YOCTO_VERSION}/$BUILDDIR."
+    log "Removing old build in $SCRIPTPATH/../../$BUILD_DIR."
     log "This might take a while ..."
-    rm -rf $SCRIPTPATH/../${YOCTO_VERSION}/$BUILDDIR
+    rm -rf $SCRIPTPATH/../../$BUILD_DIR
 fi
-
-cd $SCRIPTPATH/../${YOCTO_VERSION}
-
-# Configure build
-$SCRIPTPATH/generate-conf-notes.sh $SCRIPTPATH/../yocto-all/meta-resin/meta-resin-${YOCTO_VERSION##*-}/conf $DEVICE_TYPES_JSON $YOCTO_VERSION
 
 RESIN_MACHINE_LAYER=$(ls ${SCRIPTPATH}/../../layers/ | grep meta-resin-)
 
+# Configure build
+
+$SCRIPTPATH/generate-conf-notes.sh $SCRIPTPATH/../../layers/${RESIN_MACHINE_LAYER}/conf/ ${DEVICE_TYPES_JSONS}
+
 export TEMPLATECONF=${SCRIPTPATH}/../../layers/${RESIN_MACHINE_LAYER}/conf/samples
-source ${SCRIPTPATH}/../../layers/poky/oe-init-build-env ${SCRIPTPATH}/../../${BUILDDIR}
+source ${SCRIPTPATH}/../../layers/poky/oe-init-build-env ${SCRIPTPATH}/../../${BUILD_DIR}
 if [ "x$STAGING" == "xyes" ]; then
     sed -i "s/.*RESIN_STAGING_BUILD ?=.*/RESIN_STAGING_BUILD ?= \"yes\"/g" conf/local.conf
 fi
@@ -407,7 +381,7 @@ fi
 if [ -n "$SHARED_SSTATE" ]; then
     sed -i "s#.*SSTATE_DIR ?=.*#SSTATE_DIR ?= \"$SHARED_SSTATE\"#g" conf/local.conf
 fi
-log "Resin build initialized in $BUILDDIR."
+log "Resin build initialized in $BUILD_DIR."
 
 # Start builds
 if [ "$DRY_RUN" == "yes" ]; then
@@ -420,28 +394,37 @@ else
       ITERATOR_MACHINES="$MACHINES"
   fi
   for machine in $ITERATOR_MACHINES; do
-      IMAGE=`cat $DEVICE_TYPES_JSON | jq  -r '.[].yocto | select(.machine == '\"${machine}\"').image'`
-      if [ -z "$IMAGE" ] || [ "z$IMAGE" == "znull" ]; then
+      for json in ${DEVICE_TYPES_JSONS}; do
+        MACHINE_IN_JSON=`cat $json | jq  -r '.yocto.machine'`
+        if [[ "$machine" != "${MACHINE_IN_JSON}" ]]; then
+          continue
+        fi
+        IMAGE=`cat $json | jq  -r '.yocto | select(.machine == '\"${machine}\"').image'`
+        if [ -z "$IMAGE" ] || [ "z$IMAGE" == "znull" ]; then
           log ERROR "No target image defined for $machine."
-      fi
-      log "Run build for $machine: MACHINE=$machine bitbake $IMAGE $BITBAKEARGS"
-      log "This might take a while ..."
-      env MACHINE=$machine bitbake ${IMAGE} $BITBAKEARGS
-      if [ $? -eq 0 ]; then
+        fi
+        log "Run build for $machine: MACHINE=$machine bitbake $IMAGE $BITBAKEARGS"
+        log "This might take a while ..."
+        env MACHINE=$machine bitbake ${IMAGE} $BITBAKEARGS
+        if [ $? -eq 0 ]; then
           log "Build for $machine suceeded."
-      else
-          log "Build for $machine failed. Check failed log in $BUILDDIR/tmp/log/cooker/$machine ."
+        else
+          log "Build for $machine failed. Check failed log in $BUILD_DIR/tmp/log/cooker/$machine ."
           EXIT_CODE=2 # Fail at the end
-      fi
+        fi
+      done
   done
+
   for machine in $ITERATOR_MACHINES; do
-        IMAGE=`cat $DEVICE_TYPES_JSON | jq  -r '.[].yocto | select(.machine == '\"${machine}\"').image'`
-        FSTYPE=`cat $DEVICE_TYPES_JSON | jq  -r '.[].yocto | select(.machine == '\"${machine}\"').fstype'`
+    for json in ${DEVICE_TYPES_JSONS}; do
+        IMAGE=`cat $json | jq  -r '.yocto | select(.machine == '\"${machine}\"').image'`
+        FSTYPE=`cat $json | jq  -r '.yocto | select(.machine == '\"${machine}\"').fstype'`
         if [ -z "$IMAGE" ] || [ -z "$FSTYPE" ] || [ "z$IMAGE" == "znull" ] || [ "z$FSTYPE" == "znull" ]; then
           log ERROR "No target image and/or fstype defined for $machine."
       fi
         log "If build for $machine succeeded, final image should have been generated here:"
-        log "   $BUILDDIR/tmp/deploy/images/$machine/$IMAGE-$machine.$FSTYPE"
+        log "   $BUILD_DIR/tmp/deploy/images/$machine/$IMAGE-$machine.$FSTYPE"
+    done
   done
 fi
 
